### ISSUE TITLE
Consider adding pip to the provides API

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/cpython#167]
The cpython buildpack installs `cpython` but along with it comes the `pip` tool.<sup>[[1]](https://docs.python.org/3/installing/index.html#key-terms)</sup> This is just like getting `npm` along with `node-engine`. We should consider having a similar API for this buildpack with cpython also providing pip as an alternative buildplan.
Note: We do have a [pip buildpack](https://github.com/paketo-community/pip) that lets users pick a version of pip.

**Comment by fg-j** [comment]
@arjun024 What use cases does this enable? Are they still relevant?
