### ISSUE TITLE
Dependency tests should verify SSL support

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/cpython#448]
Since `libssl` is dynamically linked and the library versions for `bionic` and `jammy` are not compatible, let's verify in our dependency tests that `cpython` is able to use this library.

Here are some possible ways to check:
- https://stackoverflow.com/a/37055809
- https://stackoverflow.com/a/40455989

**Comment by robdimsdale** [comment]
This is done - the SSL dependency integration test is [here](https://github.com/paketo-buildpacks/cpython/blob/bdce6ad39824547171bcc64cc94d26367588b00c/dependency/test/entrypoint.sh#L107).
