### ISSUE TITLE
Open Source pre-built Process

### ISSUE THREAD

**Issue by ajdergute** [paketo-buildpacks/cpython#577]
As a enterprise user I want to reproduce how pass l Python is build. This leads to higher trust in using this Buildpacks.

## Possible Solution

Point me to the repo which build this binaries.

## Motivation

We must ensure that nothing compromises the built artefact.

**Comment by robdimsdale** [comment]
You're in the right place - take a look at: https://github.com/paketo-buildpacks/cpython/tree/main/dependency

**Comment by ajdergute** [comment]
Thank you a lot. Maybe someone could add some sentence in README of this project to point to this documentation.

So thanks again
