### ISSUE TITLE
Include Python 3.11.7 and/or 3.12.1

### ISSUE THREAD

**Issue by JaykeMeijer** [paketo-buildpacks/cpython#691]
When can we expect this buildpack to provide the latest Python versions that have been released 1.5 months ago?

## Describe the Enhancement

Support for Python 3.11.7 and/or 3.12.1

## Motivation

At my company, we must use Paketo buildpacks, but our security scanner flags both 3.11.6 (due to the `setuptools` issue discussed in https://github.com/paketo-buildpacks/cpython/issues/579) and 3.12.0 as security risks and will not allow our builds to succeed. We are now stuck until this buildpack supports the latest Python versions.

**Comment by loewenstein** [comment]
Looking at the buildpack.toml, the requested versions have been included already.

@paketo-buildpacks/python-maintainers Should this be closed?

**Comment by arjun024** [comment]
Available since https://github.com/paketo-buildpacks/cpython/releases/tag/v1.11.1
